version: '3.8'

services:
  viper-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viper-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./.streamlit:/app/.streamlit
    environment:
      - DB_FILE_NAME=/app/data/threat_intel_gemini_mvp.db
      # You can add your API keys and other configuration here
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - EXPLOIT_DB_API_URL=${EXPLOIT_DB_API_URL:-}
      - LOG_LEVEL=INFO
    restart: unless-stopped
    # Use bridge networking (default)
    # network_mode: "host"

volumes:
  data:
    driver: local
