[server]
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "127.0.0.1"
serverPort = 8501
gatherUsageStats = false

[theme]
# Modern theme with red and dark accents
primaryColor="#FF4B4B"        # Red for primary actions/highlights
backgroundColor="#0E1117"     # Dark background
secondaryBackgroundColor="#262730"  # Slightly lighter background for cards/containers
textColor="#FAFAFA"           # Light text for better contrast
font="monospace"              # Monospace font for that tech feel
